name: toptom_widgetbook
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1
homepage: https://github.com/COMPANY-GLOBAL-ID/toptom_widgetbook

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  calendar_date_picker2: ^1.0.2
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icon_font_generator: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: ToptomIcons
      fonts:
        - asset: assets/icons/ToptomIcons.ttf
