name: toptom_widgetbook
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  calendar_date_picker2: ^0.5.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icon_font_generator: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: ToptomIcons
      fonts:
        - asset: assets/icons/ToptomIcons.ttf
