name: toptom_widgetbook
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  widgetbook_annotation: ^3.1.0
  widgetbook: ^3.7.1
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  markdown_widget: ^2.3.2+3
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  mask_text_input_formatter: ^2.8.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
