name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: 3.19.6
      - name: Install SSH key
        uses: appleboy/ssh-action@master
      - name: "Pub get"
        run: flutter pub get
        working-directory: example
      - name: "Build APK"
        run: flutter build apk --no-tree-shake-icons
        working-directory: example
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          message: "|
          🚀 *New widget book APK Built !*

          **Commit Information:**
          - Author: ${{ github.event.head_commit.author.name }}
          - Commit Message: ${{ github.event.head_commit.message }}
          - Commit URL: ${{ github.event.repository.url }}/commit/${{ github.sha }})"
          document: example/build/app/outputs/flutter-apk/app-release.apk
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
